from django.urls import path, include
from api.api.mixins import (ProductListApiView,
                             ProductDetailApiView,
                               ProductCreateApiView,
                                 ProductUpdateApiView,
                                   ProductDeleteApiView)
from api.api.api import product_api_view
from .views import home

app_name = 'api'

urlpatterns = [
    path('', home, name='home'),
    path('product/', product_api_view, name='product_api_view'),
    path('product/<int:pk>/', product_api_view, name='product_api_view_detail'),
    path('', include('api.routers')), #cette ligne de code inclut les URL définies dans le module routers de l'application api. En utilisant include, nous pouvons regrouper les URL liées à une fonctionnalité spécifique (comme les routes pour les produits) dans un module séparé, ce qui rend le code plus organisé et maintenable. Cela permet également de réutiliser les URL définies dans le module routers dans d'autres parties de l'application si nécessaire.
    path('v2/product-list/', ProductListApiView.as_view(), name='product_list_api_view'), #cette ligne de code définit une URL pour la vue ProductListApiView. En utilisant as_view(), nous convertissons la classe de vue en une vue fonctionnelle qui peut être utilisée pour gérer les requêtes HTTP. Lorsque les clients de l'API envoient une requête GET à l'URL associée à cette vue (par exemple, http://localhost:8000/api/v1/product-list/), la méthode get de ProductListApiView sera appelée pour traiter la demande et retourner une réponse contenant la liste des produits sérialisés. En définissant cette URL, nous permettons aux clients de l'API d'accéder facilement à la fonctionnalité de liste des produits via une URL dédiée.
    path('v2/product-detail/<int:pk>/', ProductDetailApiView.as_view(), name='product_detail_api_view'), #cette ligne de code définit une URL pour la vue ProductDetailApiView. En utilisant as_view(), nous convertissons la classe de vue en une vue fonctionnelle qui peut être utilisée pour gérer les requêtes HTTP. Lorsque les clients de l'API envoient une requête GET à l'URL associée à cette vue (par exemple, http://localhost:8000/api/v1/product-detail/1/), la méthode get de ProductDetailApiView sera appelée pour traiter la demande et retourner une réponse contenant les détails du produit avec l'ID spécifié (dans cet exemple, l'ID 1). De même, en utilisant la méthode put, les clients peuvent mettre à jour un produit existant en envoyant une requête PUT à l'URL associée à cette vue avec les données mises à jour pour le produit. Enfin, en utilisant la méthode delete, les clients peuvent supprimer un produit de la base de données en envoyant une requête DELETE à l'URL associée à cette vue. En définissant cette URL, nous permettons aux clients de l'API d'accéder facilement à la fonctionnalité de détail des produits via une URL dédiée.
    path('v2/product-create/', ProductCreateApiView.as_view(), name='product_create_api_view'), #cette ligne de code définit une URL pour la vue ProductCreateApiView. En utilisant as_view(), nous convertissons la classe de vue en une vue fonctionnelle qui peut être utilisée pour gérer les requêtes HTTP. Lorsque les clients de l'API envoient une requête POST à l'URL associée à cette vue (par exemple, http://localhost:8000/api/v1/product-create/), la méthode post de ProductCreateApiView sera appelée pour traiter la demande et créer un nouveau produit dans la base de données. En définissant cette URL, nous permettons aux clients de l'API d'accéder facilement à la fonctionnalité de création des produits via une URL dédiée.
    path('v2/product-update/<int:pk>/', ProductUpdateApiView.as_view(), name='product_update_api_view'), #cette ligne de code définit une URL pour la vue ProductUpdateApiView. En utilisant as_view(), nous convertissons la classe de vue en une vue fonctionnelle qui peut être utilisée pour gérer les requêtes HTTP. Lorsque les clients de l'API envoient une requête PUT à l'URL associée à cette vue (par exemple, http://localhost:8000/api/v1/product-update/1/), la méthode put de ProductUpdateApiView sera appelée pour traiter la demande et mettre à jour le produit existant avec l'ID spécifié (dans cet exemple, l'ID 1) dans la base de données. En définissant cette URL, nous permettons aux clients de l'API d'accéder facilement à la fonctionnalité de mise à jour des produits via une URL dédiée.
    path('v2/product-delete/<int:pk>/', ProductDeleteApiView.as_view(), name='product_delete_api_view'), #cette ligne de code définit une URL pour la vue ProductDeleteApiView. En utilisant as_view(), nous convertissons la classe de vue en une vue fonctionnelle qui peut être utilisée pour gérer les requêtes HTTP. Lorsque les clients de l'API envoient une requête DELETE à l'URL associée à cette vue (par exemple, http://localhost:8000/api/v1/product-delete/1/), la méthode delete de ProductDeleteApiView sera appelée pour traiter la demande et supprimer le produit existant avec l'ID spécifié (dans cet exemple, l'ID 1) de la base de données. En définissant cette URL, nous permettons aux clients de l'API d'accéder facilement à la fonctionnalité de suppression des produits via une URL dédiée.
]
