"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!^$f*@@1m7)slw%73*i65^rkv(7mraq#gqp6xfgb13#!-kfzf('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #Third party apps
    'rest_framework',

    #local api
    'api',
]

REST_FRAMEWORK = { # cette section de code est utilisée pour configurer les paramètres de Django REST Framework dans l'application Django. En particulier, la clé 'DEFAULT_PARSER_CLASSES' spécifie les classes de parsers par défaut que Django REST Framework utilisera pour analyser les données entrantes dans les requêtes HTTP. Dans ce cas, la configuration indique que le parser par défaut est 'rest_framework.parsers.JSONParser', ce qui signifie que lorsque l'application reçoit des données au format JSON, elle utilisera ce parser pour les analyser et les convertir en objets Python utilisables dans les vues et les sérialiseurs. En résumé, cette configuration indique que l'application attend des données au format JSON pour les requêtes entrantes. parser signifie que l'application peut traiter les données entrantes dans les requêtes HTTP, et JSONParser est un parser spécifique qui gère les données au format JSON.
    'DEFAULT_PARSER_CLASSES':[
        'rest_framework.parsers.JSONParser', #cette ligne de code spécifie que le parser par défaut pour les requêtes entrantes dans l'application Django REST Framework est le JSONParser. Cela signifie que lorsque l'application reçoit des données au format JSON, elle utilisera ce parser pour les analyser et les convertir en objets Python utilisables dans les vues et les sérialiseurs. En résumé, cette configuration indique que l'application attend des données au format JSON pour les requêtes entrantes.
        'rest_framework.parsers.FormParser', #cette ligne de code spécifie que le parser FormParser est également inclus dans la liste des parsers par défaut pour les requêtes entrantes dans l'application Django REST Framework. Le FormParser est utilisé pour analyser les données envoyées via des formulaires HTML, généralement avec le type de contenu "application/x-www-form-urlencoded". En incluant ce parser, l'application peut traiter à la fois les données au format JSON et les données envoyées via des formulaires HTML, offrant ainsi une plus grande flexibilité dans la manière dont les clients peuvent interagir avec l'API.
        'rest_framework.renderers.BrowsableAPIRenderer', #cette ligne de code spécifie que le renderer par défaut pour les réponses sortantes dans l'application Django REST Framework est le BrowsableAPIRenderer. Le BrowsableAPIRenderer est un renderer qui génère une interface utilisateur conviviale pour les API, permettant aux développeurs et aux utilisateurs de naviguer facilement à travers les points de terminaison de l'API, d'explorer les données et de tester les requêtes directement depuis le navigateur. En incluant ce renderer, l'application offre une expérience utilisateur améliorée lors de l'interaction avec l'API via un navigateur web.
        
    ]
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
