from api.models import Product
from api.api.serializers import ProductSerializer1
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, CreateModelMixin, UpdateModelMixin, DestroyModelMixin
from rest_framework.generics import GenericAPIView


class ProductListApiView(ListModelMixin, GenericAPIView): # Par ici on utilise ListModelMixin pour gérer les opérations de liste (GET) sur les produits. Cela signifie que cette vue est conçue pour retourner une liste de produits lorsqu'une requête GET est effectuée.
    queryset = Product.objects.all() #cette ligne de code définit le queryset de base pour cette vue, qui est une collection de tous les objets Product dans la base de données. Le queryset est utilisé pour récupérer les données à partir de la base de données et les fournir à la vue pour traitement.
    serializer_class = ProductSerializer1 #cette ligne de code spécifie que la classe de sérialiseur utilisée pour cette vue est ProductSerializer1. Le sérialiseur est responsable de convertir les instances de modèle en formats de données appropriés (comme JSON) et vice versa. En définissant serializer_class, nous indiquons à la vue quel sérialiseur utiliser pour traiter les données des produits.
    def get(self, request, *args, **kwargs): #cette méthode définit la logique pour gérer les requêtes GET envoyées à cette vue. Lorsqu'une requête GET est effectuée, cette méthode est appelée pour traiter la demande et retourner une réponse appropriée.
        return self.list(request, *args, **kwargs) #cette ligne de code utilise la méthode list fournie par le mixin ListModelMixin pour traiter la requête GET. La méthode list est responsable de récupérer les données à partir du queryset, de les sérialiser à l'aide du sérialiseur spécifié (ProductSerializer1 dans ce cas) et de construire une réponse HTTP contenant les données sérialisées. En appelant self.list, nous déléguons la logique de traitement de la requête GET au mixin, ce qui simplifie le code de la vue et permet de réutiliser la logique de liste fournie par le mixin.


class ProductDetailApiView(RetrieveModelMixin, GenericAPIView): # Par ici on utilise RetrieveModelMixin pour gérer les opérations de récupération (GET) sur les produits. Cela signifie que cette vue est conçue pour retourner les détails d'un produit spécifique lorsqu'une requête GET est effectuée avec l'ID du produit.
    queryset = Product.objects.all() #cette ligne de code définit le queryset de base pour cette vue, qui est une collection de tous les objets Product dans la base de données. Le queryset est utilisé pour récupérer les données à partir de la base de données et les fournir à la vue pour traitement.
    serializer_class = ProductSerializer1 #cette ligne de code spécifie que la classe de
    
    #en utilisant la methode get, les clients de l'API peuvent envoyer une requête GET à l'URL associée à cette vue pour obtenir les détails d'un produit spécifique en utilisant son ID. Par exemple, si un client envoie une requête GET à http://localhost:8000/api/v1/products/1/, la réponse contiendra les données sérialisées du produit avec l'ID 1, ce qui permet aux clients d'accéder facilement à ces informations via l'API. De même, en utilisant la méthode put, les clients peuvent mettre à jour un produit existant en envoyant une requête PUT à l'URL associée à cette vue avec les données mises à jour pour le produit. Enfin, en utilisant la méthode delete, les clients peuvent supprimer un produit de la base de données en envoyant une requête DELETE à l'URL associée à cette vue.
    def get(self, request, *args, **kwargs): #cette methode définit la logique pour gérer les requêtes GET envoyées à cette vue. Lorsqu'une requête GET est effectuée, cette méthode est appelée pour traiter la demande et retourner une réponse appropriée.
        return self.retrieve(request, *args, **kwargs) #cette ligne de code utilise la méthode list fournie par le mixin ListModelMixin pour traiter la requête GET. La méthode list est responsable de récupérer les données à partir du queryset, de les sérialiser à l'aide du sérialiseur spécifié (ProductSerializer1 dans ce cas) et de construire une réponse HTTP contenant les données sérialisées. En appelant self.list, nous déléguons la logique de traitement de la requête GET au mixin, ce qui simplifie le code de la vue et permet de réutiliser la logique de liste fournie par le mixin.
    
    
class ProductCreateApiView(CreateModelMixin, GenericAPIView): # Par ici on utilise CreateModelMixin pour gérer les opérations de création (POST) sur les produits. Cela signifie que cette vue est conçue pour permettre aux clients de l'API de créer de nouveaux produits en envoyant une requête POST avec les données du produit à créer.
    queryset = Product.objects.all() #cette ligne de code définit le queryset de base pour cette vue, qui est une collection de tous les objets Product dans la base de données. Le queryset est utilisé pour récupérer les données à partir de la base de données et les fournir à la vue pour traitement.
    serializer_class = ProductSerializer1 #cette ligne de code spécifie que la classe de sérialiseur utilisée pour cette vue est ProductSerializer1. Le sérialiseur est responsable de convertir les instances de modèle en formats de données appropriés (comme JSON) et vice versa. En définissant serializer_class, nous indiquons à la vue quel sérialiseur utiliser pour traiter les données des produits.

    #en utilisant la methode post, les clients de l'API peuvent envoyer une requête POST à l'URL associée à cette vue pour créer un nouveau produit en fournissant les données nécessaires dans le corps de la requête. Par exemple, si un client envoie une requête POST à http://localhost:8000/api/v1/products/ avec les données du produit à créer, la vue traitera la demande de création en utilisant la logique définie dans la méthode post. La réponse contiendra les données sérialisées du nouveau produit créé, ce qui permet aux clients d'accéder facilement à ces informations via l'API.
    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs) #cette ligne de code utilise la méthode create fournie par le mixin CreateModelMixin pour traiter la requête POST. La méthode create est responsable de valider les données fournies dans la requête, de créer un nouvel objet dans la base de données avec ces données et de construire une réponse HTTP appropriée. En appelant self.create, nous déléguons la logique de traitement de la requête POST au mixin, ce qui simplifie le code de la vue et permet de réutiliser la logique de création fournie par le mixin.

class ProductUpdateApiView(UpdateModelMixin, GenericAPIView): # Par ici on utilise UpdateModelMixin pour gérer les opérations de mise à jour (PUT) sur les produits. Cela signifie que cette vue est conçue pour permettre aux clients de l'API de mettre à jour les produits existants en envoyant une requête PUT avec les données mises à jour du produit.
    queryset = Product.objects.all() #cette ligne de code définit le queryset de base pour cette vue, qui est une collection de tous les objets Product dans la base de données. Le queryset est utilisé pour récupérer les données à partir de la base de données et les fournir à la vue pour traitement.
    serializer_class = ProductSerializer1 #cette ligne de code spécifie que la classe de sérialiseur utilisée pour cette vue est ProductSerializer1. Le sérialiseur est responsable de convertir les instances de modèle en formats de données appropriés (comme JSON) et vice versa. En définissant serializer_class, nous indiquons à la vue quel sérialiseur utiliser pour traiter les données des produits.

    #en utilisant la methode put, les clients de l'API peuvent envoyer une requête PUT à l'URL associée à cette vue pour mettre à jour un produit existant en fournissant les données mises à jour dans le corps de la requête. Par exemple, si un client envoie une requête PUT à http://localhost:8000/api/v1/products/1/ avec les données mises à jour du produit avec l'ID 1, la vue traitera la demande de mise à jour en utilisant la logique définie dans la méthode put. La réponse contiendra les données sérialisées du produit mis à jour, ce qui permet aux clients d'accéder facilement à ces informations via l'API.
    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs) #cette ligne de code utilise la méthode update fournie par le mixin UpdateModelMixin pour traiter la requête PUT. La méthode update est responsable de valider les données fournies dans la requête, de mettre à jour l'objet existant dans la base de données avec ces données et de construire une réponse HTTP appropriée. En appelant self.update, nous déléguons la logique de traitement de la requête PUT au mixin, ce qui simplifie le code de la vue et permet de réutiliser la logique de mise à jour fournie par le mixin.
    
    #en utilisant la methode patch, les clients de l'API peuvent envoyer une requête PATCH à l'URL associée à cette vue pour mettre à jour partiellement un produit existant en fournissant les données mises à jour dans le corps de la requête. Par exemple, si un client envoie une requête PATCH à http://localhost:8000/api/v1/products/1/ avec les données mises à jour du produit avec l'ID 1, la vue traitera la demande de mise à jour partielle en utilisant la logique définie dans la méthode patch. La réponse contiendra les données sérialisées du produit mis à jour, ce qui permet aux clients d'accéder facilement à ces informations via l'API.
    def patch(self, request, *args, **kwargs): #cette méthode définit la logique pour gérer les requêtes PATCH envoyées à cette vue. Lorsqu'une requête PATCH est effectuée, cette méthode est appelée pour traiter la demande et retourner une réponse appropriée.
        return self.partial_update(request, *args, **kwargs) #cette ligne de code utilise la méthode partial_update fournie par le mixin UpdateModelMixin pour traiter la requête PATCH. La méthode partial_update est responsable de valider les données fournies dans la requête, de mettre à jour partiellement l'objet existant dans la base de données avec ces données et de construire une réponse HTTP appropriée. En appelant self.partial_update, nous déléguons la logique de traitement de la requête PATCH au mixin, ce qui simplifie le code de la vue et permet de réutiliser la logique de mise à jour partielle fournie par le mixin.
    
class ProductDeleteApiView(DestroyModelMixin, GenericAPIView): # Par ici on utilise DestroyModelMixin pour gérer les opérations de suppression (DELETE) sur les produits. Cela signifie que cette vue est conçue pour permettre aux clients de l'API de supprimer des produits existants en envoyant une requête DELETE avec l'ID du produit à supprimer.
    queryset = Product.objects.all() #cette ligne de code définit le queryset de base pour cette vue, qui est une collection de tous les objets Product dans la base de données. Le queryset est utilisé pour récupérer les données à partir de la base de données et les fournir à la vue pour traitement.
    serializer_class = ProductSerializer1 #cette ligne de code spécifie que la classe de sérialiseur utilisée pour cette vue est ProductSerializer1. Le sérialiseur est responsable de convertir les instances de modèle en formats de données appropriés (comme JSON) et vice versa. En définissant serializer_class, nous indiquons à la vue quel sérialiseur utiliser pour traiter les données des produits.

    #en utilisant la methode delete, les clients de l'API peuvent envoyer une requête DELETE à l'URL associée à cette vue pour supprimer un produit existant en utilisant son ID. Par exemple, si un client envoie une requête DELETE à http://localhost:8000/api/v1/products/1/, la vue traitera la demande de suppression en utilisant la logique définie dans la méthode delete. La réponse indiquera si la suppression a été effectuée avec succès ou s'il y a eu une erreur, ce qui permet aux clients d'accéder facilement à ces informations via l'API.
    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs) #cette ligne de code utilise la méthode destroy fournie par le mixin DestroyModelMixin pour traiter la requête DELETE. La méthode destroy est responsable de supprimer l'objet existant dans la base de données correspondant à l'ID spécifié dans la requête et de construire une réponse HTTP appropriée. En appelant self.destroy, nous déléguons la logique de traitement de la requête DELETE au mixin, ce qui simplifie le code de la vue et permet de réutiliser la logique de suppression fournie par le mixin.
    
#le fichier mixins.py contient des classes de vues basées sur des mixins pour gérer les opérations CRUD (Create, Read, Update, Delete) sur les produits. Chaque classe de vue utilise un mixin spécifique pour gérer une opération particulière, ce qui permet de simplifier le code et de réutiliser la logique fournie par les mixins. Les clients de l'API peuvent interagir avec ces vues en envoyant des requêtes HTTP appropriées (GET, POST, PUT, PATCH, DELETE) à l'URL associée à chaque vue pour effectuer les opérations correspondantes sur les produits.
#l'avantage de ce fichier est qu'il permet de séparer la logique de chaque opération CRUD dans des classes de vues distinctes, ce qui rend le code plus organisé et facile à maintenir. De plus, en utilisant les mixins fournis par Django REST Framework, nous pouvons bénéficier de fonctionnalités préconstruites pour gérer les opérations courantes sur les modèles, ce qui réduit le besoin d'écrire du code personnalisé pour chaque opération.

